# Generated by Django 5.0.7 on 2024-10-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
