# Generated by Django 5.0.7 on 2024-10-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogApp", "0002_alter_profile_bio_alter_profile_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="name",
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
    ]
