# Generated by Django 5.0.7 on 2024-10-07 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogApp", "0004_category_tag_blogpost"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="blogpost",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="blog_images/"),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="category",
            field=models.ForeignKey(
                default="Default Category",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="blogApp.category",
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
