# Generated by Django 5.0.7 on 2024-10-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogApp", "0006_alter_blogpost_author_alter_blogpost_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="category",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
