# Generated by Django 5.0.7 on 2024-10-07 10:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blogApp", "0008_alter_blogpost_category"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BlogPost",
        ),
    ]
