# Generated by Django 5.0.7 on 2024-10-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogApp", "0010_blogpost"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="blog_images/"),
        ),
    ]
