# Generated by Django 5.0.7 on 2024-10-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogApp", "0011_blogpost_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="blog_posts", to="blogApp.tag"
            ),
        ),
    ]
