# Generated by Django 5.0.7 on 2024-10-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogApp", "0016_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                default="draft",
                max_length=10,
            ),
        ),
    ]
