# Generated by Django 5.0.7 on 2024-10-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogApp", "0017_blogpost_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_flagged",
            field=models.BooleanField(default=False),
        ),
    ]
