# Generated by Django 5.0.7 on 2024-10-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogApp", "0020_activitylog"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="publish_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
