# Generated by Django 5.0.7 on 2024-10-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogApp", "0021_blogpost_publish_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="draft",
                max_length=10,
            ),
        ),
    ]
