# Generated by Django 5.0.7 on 2024-10-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogApp", "0022_alter_blogpost_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="scheduled_publish_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
