# Generated by Django 5.0.7 on 2024-10-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="role",
            field=models.CharField(
                choices=[
                    ("author", "Author"),
                    ("editor", "Editor"),
                    ("moderator", "Moderator"),
                ],
                default="author",
                max_length=10,
            ),
        ),
    ]
