# Generated by Django 5.0.7 on 2024-10-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_useraccount_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="is_banned",
            field=models.BooleanField(default=False),
        ),
    ]
