# Generated by Django 5.0.7 on 2024-10-17 09:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_useraccount_is_banned"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
